### PR TITLE
support angular 4

### PR DESCRIPTION
**Pull request by i-am-dror**
change how components are included so it will compile with ng 4 applications

### CODE REVIEW

**Comment by rjsteinert** [comment]
I would love to try out this PR but either there is something wrong with this PR or I am not including it correctly.

```
ng new angular2-json-schema-form-test
cd angular2-json-schema-form-test
git clone git@github.com:i-am-dror/angular2-json-schema-form.git
cd angular2-json-schema-form
npm install
npm run compile:tsc
cd ..
# Add the following import statement in src/app/app.module.ts and also add
# JsonSchemaFormModue.forRoot() to list of NgModule imports.
#
# import { JsonSchemaFormModule } from '../../angular2-json-schema-form/dist';
vim src/app/app.module.ts
# Add material using the directions here https://material.angular.io/guide/getting-started
# but when importing Material, import everything by doing the import as described here
# https://github.com/angular/angular-cli/wiki/stories-include-angular-material
# ...
# Now start the application.
npm start
```

I get the following output:
```

> angular2-json-schema-form-test@0.0.0 start /Users/rsteinert/Git/tangerine-community/tmp/angular2-json-schema-form-test
> ng serve

** NG Live Development Server is running on http://localhost:4200 **
Hash: 40a75e2c0916f9ac3168
Time: 14464ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 166 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 364 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 65.2 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.18 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

WARNING in ./~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

ERROR in Error encountered resolving symbol values statically. Calling function 'JsonSchemaFormModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/rsteinert/Git/tangerine-community/tmp/angular2-json-schema-form-test/src/app/app.module.ts, resolving symbol AppModule in /Users/rsteinert/Git/tangerine-community/tmp/angular2-json-schema-form-test/src/app/app.module.ts
```

**Comment by i-am-dror** [comment]
@rjsteinert I'll try to reproduce it

**Comment by i-am-dror** [comment]
please try to add 
"angular2-json-schema-form": "git+https://github.com/i-am-dror/angular2-json-schema-form.git"
to your package json

npm i

# Add the following import statement in src/app/app.module.ts and also add
# JsonSchemaFormModue.forRoot() to list of NgModule imports.
#
# import { JsonSchemaFormModule } from 'angular2-json-schema-form/src';

ng serve


hope it'll help you

**Comment by bieri** [comment]
@i-am-dror i got your pr working in an angular4 app, but it required ripping out the material design framework as it would not work even when i suppressed the parse errors with a NO_ERRORS_SCHEMA

**Pull request merged**
